version: '3.9'

services:
    mysql:
        image: mysql:8.0
        container_name: ulg-mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=rootpassword
            - MYSQL_DATABASE=test
            - MYSQL_USER=testuser
            - MYSQL_PASSWORD=testpassword
        ports:
          - "8886:3306"
        volumes:
          - mysql:/var/lib/mysql

volumes:
    mysql: # Mysql persistent volume
